import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Routes, Route, Link } from "react-router-dom";
import Home from "./components/Home";
import Cart from "./components/Cart";
import { auth, db } from "./firebase/firebase.config";
import Signup from "./pages/Signup";
import Login from "./pages/Login";
import { signOut } from "firebase/auth";
import Profile from "./pages/Profile";
import AddProduct from "./pages/AddProduct";
import EditProduct from "./pages/EditProduct";
import Orders from "./pages/Orders";
import OrderDetails from "./pages/OrderDetails";
const LogoutButton = () => (_jsx("button", { onClick: () => signOut(auth), children: "Logout" }));
console.log("Auth Loaded:", auth);
console.log("DB Loaded:", db);
const App = () => {
    return (_jsxs(_Fragment, { children: [_jsxs("nav", { style: { padding: "10px", borderBottom: "1px solid #ccc" }, children: [_jsx(Link, { to: "/", style: { marginRight: "10px" }, children: "Home" }), _jsx(Link, { to: "/cart", style: { marginRight: "10px" }, children: "Cart" }), _jsx(Link, { to: "/signup", style: { marginRight: "10px" }, children: "Signup" }), _jsx(Link, { to: "/login", style: { marginRight: "10px" }, children: "Login" }), _jsx(Link, { to: "/profile", style: { marginRight: "10px" }, children: "Profile" }), _jsx(Link, { to: "/add-product", children: "Add Product" }), _jsx(Link, { to: "/orders", style: { marginRight: "10px" }, children: "Orders" }), _jsx(LogoutButton, {})] }), _jsxs(Routes, { children: [_jsx(Route, { path: "/", element: _jsx(Home, {}) }), _jsx(Route, { path: "/cart", element: _jsx(Cart, {}) }), _jsx(Route, { path: "/signup", element: _jsx(Signup, {}) }), _jsx(Route, { path: "/login", element: _jsx(Login, {}) }), _jsx(Route, { path: "/profile", element: _jsx(Profile, {}) }), _jsx(Route, { path: "/add-product", element: _jsx(AddProduct, {}) }), _jsx(Route, { path: "/edit-product/:id", element: _jsx(EditProduct, {}) }), _jsx(Route, { path: "/orders", element: _jsx(Orders, {}) }), _jsx(Route, { path: "/orders/:id", element: _jsx(OrderDetails, {}) })] })] }));
};
export default App;
